version: "3"
services:
  # interface:
  #   links:
  #     - postgres:postgres
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - webnet
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      DB_NAME: 'sreality'
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"
    expose:
    - "5432"
    networks:
      - webnet

  scrapy:
    build: ./scraper
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: 'postgres'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'secret'
      DB_NAME: 'sreality'
    depends_on:
      - postgres
  
  web:
    restart: always
    build: ./web
    environment:
      DB_HOST: 'postgres'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'secret'
      DB_NAME: 'sreality'
      DB_PORT: '5432'
    networks:
      - webnet
    volumes:
      - ./web/:/app/
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - scrapy
    
networks:
  webnet: